allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects { subproject ->
    subproject.pluginManager.withPlugin("com.android.library") {
        def android = subproject.extensions.getByName("android")
        if (android.namespace == null) {
            def manifestFile = subproject.file("src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def packageName = new XmlSlurper().parse(manifestFile).'@package'.text()
                if (packageName) {
                    android.namespace = packageName
                }
            }
        }
        android.compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
        }
    }
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
