name: flutter_ota
description: A Flutter package for OTA updating firmware of ESP32 using Bluetooth Low Energy (BLE).
version: 1.0.0
homepage: https://github.com/sparkleo-io/flutter_ota.git

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  flutter_blue_plus: ^2.3.8
  file_picker: ^11.0.2
  http: ^1.2.0
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # assets:
  #   - assets/
